src/application/app.py
import os
import babel

from flask import Flask

from . import cli
from . import jinja_filters
from .model import db, session


def create_app(config=None):
    """ Flask app factory that creates and configure the app.
    Args:
        test_config (str): python configuration filepath

    Returns: Flask application
    """
    app = Flask(__name__)
    app.config.from_pyfile("config.py")

    if config:
        app.config.update(config)

    db.init_app(app)

    # blueprints
    from .blueprints import home, user
    app.register_blueprint(home.bp)
    app.register_blueprint(user.bp, url_prefix="/users")

    # register cli commands
    app.cli.add_command(cli.init_db_command)

    # register filters
    app.jinja_env.filters["datetime"] = jinja_filters.format_datetime

    # request handlers
    @app.after_request
    def commit_db_session(response):
        session.commit()
        return response

    return app

src/application/blueprints/home.py
import logging

import flask

from ..model import db, Post, User

bp = flask.Blueprint("home", __name__)


@bp.route("/")
def index():
    """Home page, displays the feed.

    Returns:
        [str]: Flask template, as HTML string
    """
    user = db.session\
        .query(User)\
        .first()

    posts = db.session\
        .query(Post)\
        .order_by(Post.created_at.desc())\
        .all()

    return flask.render_template(
        "home.html",
        user=user,
        posts=posts
    )

src/application/blueprints/user.py
import logging

import flask

from ..model import db, User, Post

bp = flask.Blueprint("user", __name__)


@bp.route("/<string:username>")
def user(username):
    """Displays a user's profile.

    Args:
        username (str): username (e.g "bob")

    Returns:
        str: flask template as HTML string
    """
    user = db.session\
        .query(User)\
        .filter(User.username==username)\
        .first()

    return flask.render_template(
        "user.html",
        user=user
    )

src/application/templates/base.html
<!doctype html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Custom CSS & JS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='script.js') }}"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">

    <!-- favicon -->
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <title>Instalike - {% block title %}{% endblock %}</title>
</head>

<header>
    {% include "header.html" %}
</header>

<body>
    <div class="container-fluid bg-light py-5">
        {% block body %}{% endblock %}
    </div>
</body>

<footer>
    {% include "footer.html" %}
</footer>

src/application/templates/components/modal_followers.html
<div class="modal fade" id="modalFollowers"
     tabindex="-1" role="dialog"
     aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="modalFollowers">Followers</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body">
        <ul class="list-unstyled">
          {% for follower in user.followers %}
          <li class="media">
            <img class="align-self-center mr-3 rounded-circle"
                src="{{ follower.avatar }}"
                height="30px">

            <div class="media-body">
              <p class="mb-0">
                <a href="{{ url_for('user.user', username=follower.username) }}">
                  {{ follower.username }}
                </a>
              </p>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div>
</div>

src/application/templates/components/modal_follows.html
<div class="modal fade" id="modalFollows"
     tabindex="-1" role="dialog"
     aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="modalFollows">Follows</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body">
        <ul class="list-unstyled">
          {% for follows in user.follows %}
          <li class="media">
            <img class="align-self-center mr-3 rounded-circle"
                src="{{ follows.avatar }}"
                height="30px">

            <div class="media-body">
              <p class="mb-0">
                <a href="{{ url_for('user.user', username=follows.username) }}">
                  {{ follows.username }}
                </a>
              </p>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div>
</div>

src/application/templates/components/modal_likes.html
<div class="modal fade" id="modalLikes{{post.id}}"
     tabindex="-1" role="dialog"
     aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="modalLikes{{post.id}}">Likes</h5>

        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button> -->

      </div>

      <div class="modal-body">
        <ul class="list-unstyled">
          {% for like in post.likes %}
          <li class="media">
            <img class="align-self-center mr-3 rounded-circle"
                src="{{ like.avatar }}"
                height="30px">

            <div class="media-body">
              <p class="mb-0">
                <a href="{{ url_for('user.user', username=like.username) }}">
                  {{ like.username }}
                </a>
              </p>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div>
</div>

src/application/templates/components/modal_post.html
<div class="modal fade" id="modalPost{{post.id}}"
     tabindex="-1" role="dialog"
     aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="modalPost{{post.id}}">Post</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body mx-5">
        {% include "components/post_wide.html" %}
      </div>

    </div>
  </div>
</div>

src/application/templates/components/post/comments.html
<p class="card-text my-1">

    <ul class="list-unstyled">
        <li>
            <a href="{{ url_for('user.user', username=post.user.username) }}">
                {{ post.user.username }}
            </a>
            {{ post.content }}
        </li>
        {% for comment in post.comments %}
            <li class="">
                <a href="{{ url_for('user.user', username=comment.user.username) }}">
                    {{ comment.user.username }}
                </a>
                {{ comment.content }}
            </li>
        {% endfor %}
    </ul>

</p>

src/application/templates/components/post/footer.html
<small class="text-muted">Posted on {{ post.created_at | datetime}}</small>

src/application/templates/components/post/header.html
<div class="media">
    <img class="align-self-center mr-3 rounded-circle"
        src="{{ post.user.avatar }}"
        height="30px">

    <div class="media-body">
        <p class="mb-0">
            <a href="{{ url_for('user.user', username=post.user.username) }}">
                {{ post.user.username }}
            </a>
        </p>
    </div>
</div>

src/application/templates/components/post/picture.html
<img class="card-img rounded-0"
     src="{{ post.picture }}"
     alt="Card image cap">

src/application/templates/components/post/reactions.html
<p>
    <a data-toggle="modal" data-target="#modalLikes{{post.id}}">
        {{ post.likes | length }} likes
    </a>

    <br>

    <i class="fas fa-heart fa-md"></i>
    <i class="fas fa-comment-alt fa-md"></i>
    <i class="fas fa-paper-plane fa-md"></i>
</p>

src/application/templates/components/post_long.html
{% include "components/modal_likes.html" %}

<div class="card rounded-sm">
    <div class="card-header bg-white">
        {% include "components/post/header.html" %}
    </div>

    {% include "components/post/picture.html" %}

    <div class="card-body">
        <div class="row">
            <div class="col">
                {% include "components/post/reactions.html" %}
                {% include "components/post/comments.html" %}
            </div>
        </div>
    </div>

    <div class="card-footer bg-white">
        {% include "components/post/footer.html" %}
    </div>
</div>

src/application/templates/components/post_picture_only.html
{% include "components/modal_post.html" %}

<div class="card post">
    <a data-toggle="modal" data-target="#modalPost{{post.id}}">
        <img class="card-img-top" src="{{ post.picture }}">
    </a>
</div>

src/application/templates/components/post_wide.html
{% include "components/modal_likes.html" %}

<div class="card rounded-sm">
    <div class="card-header bg-white">
        {% include "components/post/header.html" %}
    </div>

    <div class="row">

        <div class="col-6">
            {% include "components/post/picture.html" %}
        </div>

        <div class="col-6">
            <div class="card-body">
                {% include "components/post/reactions.html" %}
                {% include "components/post/comments.html" %}
            </div>
        </div>

    </div>

    <div class="card-footer bg-white">
        {% include "components/post/footer.html" %}
    </div>
</div>

src/application/templates/footer.html
<footer div class="bg-white container">
    <div class="row pt-3">
       <div class="col-6">
           <p class="font-weight-bold">About</p>
           <p>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
               labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
               laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
               voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
               non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
           </p>
       </div>

        <div class="col-3">
            <p class="font-weight-bold">Social</p>

            <ul class="list-unstyled">
                <li class="list-item"><i class="fab fa-instagram"></i> <a href="">Instagram</a></li>
                <li class="list-item"><i class="fab fa-facebook"></i> <a href="">Facebook</a></li>
                <li class="list-item"><i class="fab fa-youtube"></i> <a href="">YouTube</a></li>
                <li class="list-item"><i class="fab fa-github"></i> <a href="">Github</a></li>
            </ul>
        </div>

        <div class="col-3">
           <p class="font-weight-bold">Links</p>

           <ul class="list-unstyled">
               <li class="list-item"><a href="">Link 1</a></li>
               <li class="list-item"><a href="">Link 2</a></li>
               <li class="list-item"><a href="">Link 3</a></li>
           </ul>
       </div>
    </div>

    <div class="row text-center">
        <div class="col">
           <p>Copyright</p>
       </div>
    </div>

</footer>

src/application/templates/header.html
<nav class="navbar navbar-light bg-white border-bottom">
    <div class="container">
        <span class="navbar-brand mb-0">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">Instalike</a>
        </span>

        <span class="navbar-text">
            <ul class="nav nav-pills">

                <!-- home -->
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('home.index') }}" >
                      <i class="fas fa-home fa-lg"></i>
                   </a>
                </li>

                <!-- inbox -->
                <li class="nav-item">
                  <a class="nav-link" href="#">
                      <i class="fas fa-paper-plane fa-lg"></i>
                   </a>
                </li>

                <!-- explore -->
                <li class="nav-item">
                  <a class="nav-link" href="#">
                      <i class="fas fa-compass fa-lg"></i>
                  </a>
                </li>

                <!-- notifications -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                       href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <i class="fas fa-heart fa-lg"></i>
                    </a>

                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">
                        <i class="fas fa-heart fa-sm"></i> A notification !</a>
                    </div>
                </li>

            </ul>
        </span>
    </div>
</nav>

src/application/templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block body %}

<div class="container pt-5">

    <div class="row">

        <div class="col-8">
            {% for post in posts %}
                <div class="mb-3">
                    {% include 'components/post_long.html' %}
                </div>
            {% endfor %}
        </div>

        <div class="col">
            <div class="media">
                <img class="align-self-center mr-3 rounded-circle"
                    src="{{ user.avatar }}"
                    height="75">

                <div class="media-body">
                    <h5 class="mb-0">
                        <a href="{{ url_for('user.user', username=user.username) }}">
                            {{ user.username }}
                        </a>
                    </h5>
                    <p class="mb-0">{{ user.fullname }}</p>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

src/application/templates/user.html
{% extends "base.html" %}

{% block title %} {{ user.username }} {% endblock %}

{% block body %}
{% include "components/modal_followers.html" %}
{% include "components/modal_follows.html" %}

<div class="container">

    <section>
        <div class="row pt-3 pb-5 border-bottom">
            <div class="col-3 text-center">
                <img class="rounded-circle"
                        src="{{ user.avatar }}"
                        alt="profile-pic"
                        height="150">
            </div>

            <div class="col">
                <h5>{{ user.username }}</h5>

                <p>
                    <b>{{ user.posts | length }}</b> posts
                    <a data-toggle="modal" data-target="#modalFollowers">
                        <b>{{ user.followers | length }}</b> followers
                    </a>
                    <a data-toggle="modal" data-target="#modalFollows">
                        <b>{{ user.follows | length }}</b> following
                    </a>
                </p>

                <p>
                    <b>{{ user.fullname }}</b><br>
                    {{ user.bio }}
                </p>
             </div>

        </div>

    </section>

    <section class="mt-0">
        {% if user.posts %}
            <ul class="nav nav-tabs mt-3 mb-2" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="grid-tab"
                        data-toggle="tab" href="#grid" role="tab"
                        aria-controls="home" aria-selected="true">
                        <i class="fas fa-th"></i> Grid</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" id="list-tab"
                        data-toggle="tab" href="#list" role="tab"
                        aria-controls="profile" aria-selected="false">
                        <i class="fas fa-ellipsis-v"></i> List</a></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" id="likes-tab"
                        data-toggle="tab" href="#likes" role="tab"
                        aria-controls="profile" aria-selected="false">
                        <i class="fas fa-heart"></i> Likes</a></a>
                </li>
            </ul>

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="grid"
                    role="tabpanel" aria-labelledby="grid-tab">

                    <div class="card-columns">
                        {% for post in user.posts %}
                            {% include "components/post_picture_only.html" %}
                        {% endfor %}
                    </div>

                </div>

                <div class="tab-pane fade" id="list"
                    role="tabpanel" aria-labelledby="list-tab">

                    <div class="row justify-content-md-center">
                        <div class="col-8">
                            {% for post in user.posts %}
                                <div class="mb-3">
                                    {% include 'components/post_long.html' %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>

                <div class="tab-pane fade" id="likes"
                    role="tabpanel" aria-labelledby="likes-tab">

                    <div class="card-columns">
                        {% for post in user.likes %}
                            {% include "components/post_picture_only.html" %}
                        {% endfor %}
                    </div>

                </div>

            </div>
        {% else %}
            <p class="text-center">{{ user.username }} has no posts, yet.</p>
        {% endif %}
    </section>





    </section>

</div>
{% endblock %}